[package]
name = "scrapbox-cli"
version = "0.1.0"
edition = "2021"

[dependencies]
reqwest = { version = "0.11", features = ["json"] }
tokio = { version = "1", features = ["full"] }
dotenv = "0.15"
structopt = "0.3"
chrono = "0.4"
serde_json = "1.0"