[package]
name = "scrapbox-cli"
version = "0.1.0"
edition = "2021"

[dependencies]
headless_chrome = "1.0.10"
tokio = { version = "1.0", features = ["full"] }
dotenv = "0.15"
chrono = "0.4"
structopt = "0.3"
anyhow = "1.0"
urlencoding = "2.1.0"